### ISSUE TITLE
Acquire Currency Rate

### ISSUE THREAD

**Issue by yamin8000** [TradersTeam/coinex4j#3]
https://github.com/coinexcom/coinex_exchange_api/wiki/070currency_rate
Create interface for this API and model classes if needed
@ariantron

**Comment by ariantron** [comment]
6c9fdfcb017375ca09ba6ecf91ccc34d652acaf0

**Comment by ariantron** [comment]
8d8f8bf68b877b38accdd74f321f4322445e813f
